version: 2

models:
  - name: fct_finance_campaigns_day
    description: "Tabla diaria que une finanzas con marketing."
    columns:
      - name: date
        tests:
          - unique
          - not_null
      - name: ads_margin
        description: "Margen operativo menos costo de anuncios"

  - name: finance_campaigns_month
    description: "Tabla mensual agregada para el equipo de finanzas."
    columns:
      - name: datemonth
        tests:
          - unique
          - not_null
