version: 2

sources:
  - name: raw
    database: quiet-seer-299408
    schema: gz_raw_data
    loader: bigquery
    config:
     freshness:
      warn_after: {count: 90, period: day}
      loaded_at_field: "CAST(date_date AS TIMESTAMP)"  # o el campo que indique cuándo se cargó
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for a given order
      # ... (el resto de las tablas sigue igual)   