version: 2

sources:
  - name: raw
    database: quiet-seer-299408
    schema: gz_raw_data
    config:
      freshness:
        warn_after: {count: 90, period: day}
      loaded_at_field: date_date
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "sales of Greenweez / we have one row per product_id found in each orders_id"
        config:
          freshness:
            warn_after: {count: 90, period: day}
          loaded_at_field: date_date
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity
        tests:
          - dbt_utils.unique_combination_of_columns:
              arguments: # <--- Formato corregido
                combination_of_columns:
                  - orders_id
                  - pdt_id   

      - name: product
        identifier: raw_gz_product
        description: "products of Greenweez"
        columns:
          - name: products_id
            description: "Primary key"

      - name: ship
        identifier: raw_gz_ship
        description: "shipping data for Greenweez orders"
        columns:
          - name: orders_id
            description: "Primary key"
          - name: ship_cost
            tests:
              - not_null   

      - name: adwords
        identifier: raw_gz_adwords
        description: "marketing adwords"
        tests:
          - dbt_utils.unique_combination_of_columns:
              arguments: # <--- Formato corregido
                combination_of_columns: 
                  - date_date
                  - campaign_key

      - name: bing
        identifier: raw_gz_bing
        description: "marketing bing"
        tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns: 
                  - date_date
                  - campaign_key

      - name: criteo
        identifier: raw_gz_criteo
        description: "marketing criteo"
        tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns: 
                  - date_date
                  - campaign_key

      - name: facebook
        identifier: raw_gz_facebook
        description: "marketing facebook"
        tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns: 
                  - date_date
                  - campaign_key
